name: Debian Package Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and Test Package
        uses: docker://debian:sid
        with:
          args: |
            sh -c "apt-get update && \
            apt-get install -y build-essential debhelper devscripts lintian && \
            # --- PULL IDENTITY FROM GIT ---
            NAME=\$(git log -1 --pretty=format:'%an') && \
            EMAIL=\$(git log -1 --pretty=format:'%ae') && \
            export DEBFULLNAME=\"\$NAME\" && \
            export DEBEMAIL=\"\$EMAIL\" && \
            # --- NORMAL BUILD ---
            mk-build-deps -ir -t 'apt-get -y' && \
            dpkg-buildpackage -us -uc -b && \
            echo '--- RUNNING LINTIAN ---' && \
            lintian ../*.deb && \
            echo '--- RUNNING BASIC INSTALL TEST ---' && \
            dpkg -i ../*.deb"
